---
sudo: required
sevices:
  - docker

language: python
python:
  - '3.6'

env:
#- OPENSHIFT_VERSION=v3.10
  - OPENSHIFT_VERSION=v3.11

#matrix:
#  allow_failures:
#    - env: OPENSHIFT_VERSION=v3.10

script:
  # Configure test values
  - export apb_name='rhpam-apb'
  - export dockerfile='target/image/Dockerfile'
#  - export image_stream='https://raw.githubusercontent.com/jboss-container-images/rhpam-7-openshift-image/7.4.1.GA/rhpam74-image-streams.yaml'

  # workaround for bypass odcs auth
  - |
    sed -i "s/  content_sets_file: content_sets.yml//g" ${PWD}/image.yaml
  # Install and run cekit
  - pip install --pre docker docker-squash 'cekit>=3.2.0,<3.3.0' odcs
  - cekit build --overrides-file dev-overrides.yaml docker --no-squash

  # add execution permission to the test script.
  - chmod +x ${PWD}/apb-test.sh



  # Run tests.
  - ${PWD}/apb-test.sh