---
- name: "[BUSINESS CENTRAL] set service state to {{ state }}"
  k8s:
    state: '{{ state }}'
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: '{{ businesscentral_deployment_name }}'
        namespace: '{{ namespace }}'
        labels:
          app: '{{ businesscentral_deployment_name }}'
          application: '{{ application_name }}'
          service: '{{ businesscentral_service_name }}'
        annotations:
          description: All the Business Central web server's ports.
      spec:
        selector:
          deploymentConfig: '{{ businesscentral_deployment_name }}'
        ports:
          - name: http
            port: 8080
            targetPort: 8080
          - name: https
            port: 8443
            targetPort: 8443
