---
- block:
    - name: "[KIE SERVER {{ kieserver_deployment_index }}] Check H2 configuration is valid"
      shell: >
        echo "[Invalid H2 Configuration] - H2 database cannot be used with a clustered KIE Server. Choose a different option." > /dev/termination-log

    - set_fact:
        provision_failed: true
  when:
    - kieserver_db_type == 'H2'
    - kieserver_replicas > 1

- block:
    - name: "[KIE SERVER {{ kieserver_deployment_index }}] Check External DB - HA configuration is valid"
      shell: >
        echo "[Invalid HA Configuration] - External database cannot be used with more than one Set of Process Servers. Choose a different option." > /dev/termination-log

    - set_fact:
        provision_failed: true
  when:
    - kieserver_db_type == 'External'
    - kieserver_sets > 1

- block:
    - name: "[KIE SERVER {{ kieserver_deployment_index }}] Check External DB configuration is valid"
      shell: >
        echo "[Invalid DB Configuration] - Missing required parameters for external DB. Required: DRIVER, HOST, PORT, DIALECT, URL, DB_NAME" > /dev/termination-log

    - set_fact:
        provision_failed: true
  when:
    - kieserver_db_type == 'External'
    - >
      kieserver_db[kieserver_db_type].host == '' or
      kieserver_db[kieserver_db_type].port == '' or
      kieserver_db[kieserver_db_type].dialect == '' or
      kieserver_db[kieserver_db_type].driver == '' or
      kieserver_db[kieserver_db_type].name == '' or
      kieserver_db[kieserver_db_type].url == ''
